// Copyright 2024 Illumio, Inc. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        (unknown)
// source: illumio/cloud/k8scluster/v1/resource_config.proto

package k8sclusterv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Information identifying the direction of traffic in Cilium.
// https://pkg.go.dev/github.com/cilium/cilium/api/v1/flow#readme-trafficdirection
type TrafficDirection int32

const (
	TrafficDirection_TRAFFIC_DIRECTION_TRAFFIC_DIRECTION_UNKNOWN_UNSPECIFIED TrafficDirection = 0
	TrafficDirection_TRAFFIC_DIRECTION_INGRESS                               TrafficDirection = 1
	TrafficDirection_TRAFFIC_DIRECTION_EGRESS                                TrafficDirection = 2
)

// Enum value maps for TrafficDirection.
var (
	TrafficDirection_name = map[int32]string{
		0: "TRAFFIC_DIRECTION_TRAFFIC_DIRECTION_UNKNOWN_UNSPECIFIED",
		1: "TRAFFIC_DIRECTION_INGRESS",
		2: "TRAFFIC_DIRECTION_EGRESS",
	}
	TrafficDirection_value = map[string]int32{
		"TRAFFIC_DIRECTION_TRAFFIC_DIRECTION_UNKNOWN_UNSPECIFIED": 0,
		"TRAFFIC_DIRECTION_INGRESS":                               1,
		"TRAFFIC_DIRECTION_EGRESS":                                2,
	}
)

func (x TrafficDirection) Enum() *TrafficDirection {
	p := new(TrafficDirection)
	*p = x
	return p
}

func (x TrafficDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TrafficDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes[0].Descriptor()
}

func (TrafficDirection) Type() protoreflect.EnumType {
	return &file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes[0]
}

func (x TrafficDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TrafficDirection.Descriptor instead.
func (TrafficDirection) EnumDescriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{0}
}

// Information about Verdict for determining what happens to a flow
// https://pkg.go.dev/github.com/cilium/cilium/api/v1/flow#readme-verdict
type Verdict int32

const (
	Verdict_VERDICT_UNKNOWN_UNSPECIFIED Verdict = 0
	Verdict_VERDICT_FORWARDED           Verdict = 1
	Verdict_VERDICT_DROPPED             Verdict = 2
	Verdict_VERDICT_ERROR               Verdict = 3
	Verdict_VERDICT_AUDIT               Verdict = 4
	Verdict_VERDICT_REDIRECTED          Verdict = 5
	Verdict_VERDICT_TRACED              Verdict = 6
	Verdict_VERDICT_TRANSLATED          Verdict = 7
)

// Enum value maps for Verdict.
var (
	Verdict_name = map[int32]string{
		0: "VERDICT_UNKNOWN_UNSPECIFIED",
		1: "VERDICT_FORWARDED",
		2: "VERDICT_DROPPED",
		3: "VERDICT_ERROR",
		4: "VERDICT_AUDIT",
		5: "VERDICT_REDIRECTED",
		6: "VERDICT_TRACED",
		7: "VERDICT_TRANSLATED",
	}
	Verdict_value = map[string]int32{
		"VERDICT_UNKNOWN_UNSPECIFIED": 0,
		"VERDICT_FORWARDED":           1,
		"VERDICT_DROPPED":             2,
		"VERDICT_ERROR":               3,
		"VERDICT_AUDIT":               4,
		"VERDICT_REDIRECTED":          5,
		"VERDICT_TRACED":              6,
		"VERDICT_TRANSLATED":          7,
	}
)

func (x Verdict) Enum() *Verdict {
	p := new(Verdict)
	*p = x
	return p
}

func (x Verdict) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Verdict) Descriptor() protoreflect.EnumDescriptor {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes[1].Descriptor()
}

func (Verdict) Type() protoreflect.EnumType {
	return &file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes[1]
}

func (x Verdict) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Verdict.Descriptor instead.
func (Verdict) EnumDescriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{1}
}

// Information about ip version for use in IP message.
// https://pkg.go.dev/github.com/cilium/cilium/api/v1/flow#readme-ipversion
type IPVersion int32

const (
	IPVersion_IP_VERSION_IP_NOT_USED_UNSPECIFIED IPVersion = 0
	IPVersion_IP_VERSION_IPV4                    IPVersion = 1
	IPVersion_IP_VERSION_IPV6                    IPVersion = 2
)

// Enum value maps for IPVersion.
var (
	IPVersion_name = map[int32]string{
		0: "IP_VERSION_IP_NOT_USED_UNSPECIFIED",
		1: "IP_VERSION_IPV4",
		2: "IP_VERSION_IPV6",
	}
	IPVersion_value = map[string]int32{
		"IP_VERSION_IP_NOT_USED_UNSPECIFIED": 0,
		"IP_VERSION_IPV4":                    1,
		"IP_VERSION_IPV6":                    2,
	}
)

func (x IPVersion) Enum() *IPVersion {
	p := new(IPVersion)
	*p = x
	return p
}

func (x IPVersion) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (IPVersion) Descriptor() protoreflect.EnumDescriptor {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes[2].Descriptor()
}

func (IPVersion) Type() protoreflect.EnumType {
	return &file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes[2]
}

func (x IPVersion) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use IPVersion.Descriptor instead.
func (IPVersion) EnumDescriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{2}
}

// Metadata associated with a Kubernetes resource.
// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#objectmeta-v1-meta
type KubernetesObjectMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Annotations       map[string]string           `protobuf:"bytes,1,rep,name=annotations,proto3" json:"annotations,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	CreationTimestamp *timestamppb.Timestamp      `protobuf:"bytes,2,opt,name=creation_timestamp,json=creationTimestamp,proto3" json:"creation_timestamp,omitempty"`
	Kind              string                      `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	Labels            map[string]string           `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Name              string                      `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Namespace         string                      `protobuf:"bytes,6,opt,name=namespace,proto3" json:"namespace,omitempty"`
	OwnerReferences   []*KubernetesOwnerReference `protobuf:"bytes,7,rep,name=owner_references,json=ownerReferences,proto3" json:"owner_references,omitempty"`
	ResourceVersion   string                      `protobuf:"bytes,8,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	Uid               string                      `protobuf:"bytes,9,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *KubernetesObjectMetadata) Reset() {
	*x = KubernetesObjectMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesObjectMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesObjectMetadata) ProtoMessage() {}

func (x *KubernetesObjectMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesObjectMetadata.ProtoReflect.Descriptor instead.
func (*KubernetesObjectMetadata) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{0}
}

func (x *KubernetesObjectMetadata) GetAnnotations() map[string]string {
	if x != nil {
		return x.Annotations
	}
	return nil
}

func (x *KubernetesObjectMetadata) GetCreationTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.CreationTimestamp
	}
	return nil
}

func (x *KubernetesObjectMetadata) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubernetesObjectMetadata) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *KubernetesObjectMetadata) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubernetesObjectMetadata) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *KubernetesObjectMetadata) GetOwnerReferences() []*KubernetesOwnerReference {
	if x != nil {
		return x.OwnerReferences
	}
	return nil
}

func (x *KubernetesObjectMetadata) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *KubernetesObjectMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Information identifying an object owning a Kubernetes resource.
// https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.29/#ownerreference-v1-meta
type KubernetesOwnerReference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ApiVersion         string `protobuf:"bytes,1,opt,name=api_version,json=apiVersion,proto3" json:"api_version,omitempty"`
	BlockOwnerDeletion bool   `protobuf:"varint,2,opt,name=block_owner_deletion,json=blockOwnerDeletion,proto3" json:"block_owner_deletion,omitempty"`
	Controller         bool   `protobuf:"varint,3,opt,name=controller,proto3" json:"controller,omitempty"`
	Kind               string `protobuf:"bytes,4,opt,name=kind,proto3" json:"kind,omitempty"`
	Name               string `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Uid                string `protobuf:"bytes,6,opt,name=uid,proto3" json:"uid,omitempty"`
}

func (x *KubernetesOwnerReference) Reset() {
	*x = KubernetesOwnerReference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesOwnerReference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesOwnerReference) ProtoMessage() {}

func (x *KubernetesOwnerReference) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesOwnerReference.ProtoReflect.Descriptor instead.
func (*KubernetesOwnerReference) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{1}
}

func (x *KubernetesOwnerReference) GetApiVersion() string {
	if x != nil {
		return x.ApiVersion
	}
	return ""
}

func (x *KubernetesOwnerReference) GetBlockOwnerDeletion() bool {
	if x != nil {
		return x.BlockOwnerDeletion
	}
	return false
}

func (x *KubernetesOwnerReference) GetController() bool {
	if x != nil {
		return x.Controller
	}
	return false
}

func (x *KubernetesOwnerReference) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *KubernetesOwnerReference) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *KubernetesOwnerReference) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

// Metadata about the client operator and Kubernetes cluster.
// Sent as the first message in each KubernetesResources RPC request stream.
type KubernetesClusterMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Unique ID of the client operator's Kubernetes cluster.
	// This is the UID of the cluster's kube-system namespace, which is considered globally unique.
	Uid string `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	// Kubernetes version of the operator's cluster.
	// https://pkg.go.dev/k8s.io/client-go/discovery#DiscoveryClient.ServerVersion
	KubernetesVersion string `protobuf:"bytes,2,opt,name=kubernetes_version,json=kubernetesVersion,proto3" json:"kubernetes_version,omitempty"`
	// Version of the operator. This version is following the Semver 2.0.0 format, e.g. "1.2.0".
	// https://semver.org/spec/v2.0.0.html
	OperatorVersion string `protobuf:"bytes,3,opt,name=operator_version,json=operatorVersion,proto3" json:"operator_version,omitempty"`
}

func (x *KubernetesClusterMetadata) Reset() {
	*x = KubernetesClusterMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesClusterMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesClusterMetadata) ProtoMessage() {}

func (x *KubernetesClusterMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesClusterMetadata.ProtoReflect.Descriptor instead.
func (*KubernetesClusterMetadata) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{2}
}

func (x *KubernetesClusterMetadata) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *KubernetesClusterMetadata) GetKubernetesVersion() string {
	if x != nil {
		return x.KubernetesVersion
	}
	return ""
}

func (x *KubernetesClusterMetadata) GetOperatorVersion() string {
	if x != nil {
		return x.OperatorVersion
	}
	return ""
}

// Message sent by the operator in a KubernetesResources request stream.
// Message subtypes are sent in this order in each stream:
// 1. (1) cluster_metadata, to identify the client cluster and operator.
// 2. (0+) resource_metadata, one message for each resource in the cluster.
// 3. (1) resource_snapshot_complete, to indicate the initial snapshot of all resources in the cluster is complete.
// 4. (0+) resource_mutation, one message for each resource creation/update/deletion in the cluster.
type SendKubernetesResourcesRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Send any of these "request" messages that can contain any of the documented types.
	//
	// Types that are assignable to Request:
	//
	//	*SendKubernetesResourcesRequest_ClusterMetadata
	//	*SendKubernetesResourcesRequest_ResourceMetadata
	//	*SendKubernetesResourcesRequest_ResourceSnapshotComplete
	//	*SendKubernetesResourcesRequest_KubernetesResourceMutation
	Request isSendKubernetesResourcesRequest_Request `protobuf_oneof:"request"`
}

func (x *SendKubernetesResourcesRequest) Reset() {
	*x = SendKubernetesResourcesRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKubernetesResourcesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKubernetesResourcesRequest) ProtoMessage() {}

func (x *SendKubernetesResourcesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKubernetesResourcesRequest.ProtoReflect.Descriptor instead.
func (*SendKubernetesResourcesRequest) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{3}
}

func (m *SendKubernetesResourcesRequest) GetRequest() isSendKubernetesResourcesRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SendKubernetesResourcesRequest) GetClusterMetadata() *KubernetesClusterMetadata {
	if x, ok := x.GetRequest().(*SendKubernetesResourcesRequest_ClusterMetadata); ok {
		return x.ClusterMetadata
	}
	return nil
}

func (x *SendKubernetesResourcesRequest) GetResourceMetadata() *KubernetesObjectMetadata {
	if x, ok := x.GetRequest().(*SendKubernetesResourcesRequest_ResourceMetadata); ok {
		return x.ResourceMetadata
	}
	return nil
}

func (x *SendKubernetesResourcesRequest) GetResourceSnapshotComplete() *KubernetesResourceSnapshotComplete {
	if x, ok := x.GetRequest().(*SendKubernetesResourcesRequest_ResourceSnapshotComplete); ok {
		return x.ResourceSnapshotComplete
	}
	return nil
}

func (x *SendKubernetesResourcesRequest) GetKubernetesResourceMutation() *KubernetesResourceMutation {
	if x, ok := x.GetRequest().(*SendKubernetesResourcesRequest_KubernetesResourceMutation); ok {
		return x.KubernetesResourceMutation
	}
	return nil
}

type isSendKubernetesResourcesRequest_Request interface {
	isSendKubernetesResourcesRequest_Request()
}

type SendKubernetesResourcesRequest_ClusterMetadata struct {
	// Metadata about the cluster and operator.
	ClusterMetadata *KubernetesClusterMetadata `protobuf:"bytes,1,opt,name=cluster_metadata,json=clusterMetadata,proto3,oneof"`
}

type SendKubernetesResourcesRequest_ResourceMetadata struct {
	// Metadata about a Kubernetes resource in the cluster.
	ResourceMetadata *KubernetesObjectMetadata `protobuf:"bytes,2,opt,name=resource_metadata,json=resourceMetadata,proto3,oneof"`
}

type SendKubernetesResourcesRequest_ResourceSnapshotComplete struct {
	// Indicates that all resource_metadata have been sent to report all the resources in the cluster in the initial snapshot.
	ResourceSnapshotComplete *KubernetesResourceSnapshotComplete `protobuf:"bytes,3,opt,name=resource_snapshot_complete,json=resourceSnapshotComplete,proto3,oneof"`
}

type SendKubernetesResourcesRequest_KubernetesResourceMutation struct {
	// A mutation to a Kubernetes resource in the cluster.
	KubernetesResourceMutation *KubernetesResourceMutation `protobuf:"bytes,4,opt,name=kubernetes_resource_mutation,json=kubernetesResourceMutation,proto3,oneof"`
}

func (*SendKubernetesResourcesRequest_ClusterMetadata) isSendKubernetesResourcesRequest_Request() {}

func (*SendKubernetesResourcesRequest_ResourceMetadata) isSendKubernetesResourcesRequest_Request() {}

func (*SendKubernetesResourcesRequest_ResourceSnapshotComplete) isSendKubernetesResourcesRequest_Request() {
}

func (*SendKubernetesResourcesRequest_KubernetesResourceMutation) isSendKubernetesResourcesRequest_Request() {
}

// Empty on purpose since this type is just expected when snapshot stream is done.
type KubernetesResourceSnapshotComplete struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *KubernetesResourceSnapshotComplete) Reset() {
	*x = KubernetesResourceSnapshotComplete{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesResourceSnapshotComplete) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesResourceSnapshotComplete) ProtoMessage() {}

func (x *KubernetesResourceSnapshotComplete) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesResourceSnapshotComplete.ProtoReflect.Descriptor instead.
func (*KubernetesResourceSnapshotComplete) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{4}
}

// Message sent to the operator in a KubernetesResources response stream.
type SendKubernetesResourcesResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *SendKubernetesResourcesResponse) Reset() {
	*x = SendKubernetesResourcesResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendKubernetesResourcesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendKubernetesResourcesResponse) ProtoMessage() {}

func (x *SendKubernetesResourcesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendKubernetesResourcesResponse.ProtoReflect.Descriptor instead.
func (*SendKubernetesResourcesResponse) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{5}
}

// A mutation to a Kubernetes resource in the cluster.
// Each mutation contains the full resource metadata after mutation (on create or update)
// or before mutation (on delete).
type KubernetesResourceMutation struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Send any of these "mutation" messages that can contain any of
	// The documented types
	//
	// Types that are assignable to Mutation:
	//
	//	*KubernetesResourceMutation_CreateResource
	//	*KubernetesResourceMutation_UpdateResource
	//	*KubernetesResourceMutation_DeleteResource
	Mutation isKubernetesResourceMutation_Mutation `protobuf_oneof:"mutation"`
}

func (x *KubernetesResourceMutation) Reset() {
	*x = KubernetesResourceMutation{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KubernetesResourceMutation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KubernetesResourceMutation) ProtoMessage() {}

func (x *KubernetesResourceMutation) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KubernetesResourceMutation.ProtoReflect.Descriptor instead.
func (*KubernetesResourceMutation) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{6}
}

func (m *KubernetesResourceMutation) GetMutation() isKubernetesResourceMutation_Mutation {
	if m != nil {
		return m.Mutation
	}
	return nil
}

func (x *KubernetesResourceMutation) GetCreateResource() *KubernetesObjectMetadata {
	if x, ok := x.GetMutation().(*KubernetesResourceMutation_CreateResource); ok {
		return x.CreateResource
	}
	return nil
}

func (x *KubernetesResourceMutation) GetUpdateResource() *KubernetesObjectMetadata {
	if x, ok := x.GetMutation().(*KubernetesResourceMutation_UpdateResource); ok {
		return x.UpdateResource
	}
	return nil
}

func (x *KubernetesResourceMutation) GetDeleteResource() *KubernetesObjectMetadata {
	if x, ok := x.GetMutation().(*KubernetesResourceMutation_DeleteResource); ok {
		return x.DeleteResource
	}
	return nil
}

type isKubernetesResourceMutation_Mutation interface {
	isKubernetesResourceMutation_Mutation()
}

type KubernetesResourceMutation_CreateResource struct {
	// Metadata of a newly created Kubernetes resource.
	CreateResource *KubernetesObjectMetadata `protobuf:"bytes,1,opt,name=create_resource,json=createResource,proto3,oneof"`
}

type KubernetesResourceMutation_UpdateResource struct {
	// Metadata of an updated Kubernetes resource, after update.
	UpdateResource *KubernetesObjectMetadata `protobuf:"bytes,2,opt,name=update_resource,json=updateResource,proto3,oneof"`
}

type KubernetesResourceMutation_DeleteResource struct {
	// Metadata of a deleted Kubernetes resource, before deletion.
	DeleteResource *KubernetesObjectMetadata `protobuf:"bytes,3,opt,name=delete_resource,json=deleteResource,proto3,oneof"`
}

func (*KubernetesResourceMutation_CreateResource) isKubernetesResourceMutation_Mutation() {}

func (*KubernetesResourceMutation_UpdateResource) isKubernetesResourceMutation_Mutation() {}

func (*KubernetesResourceMutation_DeleteResource) isKubernetesResourceMutation_Mutation() {}

// Message representing a log entry.
type LogEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The actual log message contents, as a JSON object.
	JsonMessage string `protobuf:"bytes,3,opt,name=json_message,json=jsonMessage,proto3" json:"json_message,omitempty"`
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{7}
}

func (x *LogEntry) GetJsonMessage() string {
	if x != nil {
		return x.JsonMessage
	}
	return ""
}

// Message to encapsulate a request to send logs.
type SendLogsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Request:
	//
	//	*SendLogsRequest_LogEntry
	Request isSendLogsRequest_Request `protobuf_oneof:"request"`
}

func (x *SendLogsRequest) Reset() {
	*x = SendLogsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogsRequest) ProtoMessage() {}

func (x *SendLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogsRequest.ProtoReflect.Descriptor instead.
func (*SendLogsRequest) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{8}
}

func (m *SendLogsRequest) GetRequest() isSendLogsRequest_Request {
	if m != nil {
		return m.Request
	}
	return nil
}

func (x *SendLogsRequest) GetLogEntry() *LogEntry {
	if x, ok := x.GetRequest().(*SendLogsRequest_LogEntry); ok {
		return x.LogEntry
	}
	return nil
}

type isSendLogsRequest_Request interface {
	isSendLogsRequest_Request()
}

type SendLogsRequest_LogEntry struct {
	// A single log entry to be sent.
	LogEntry *LogEntry `protobuf:"bytes,1,opt,name=log_entry,json=logEntry,proto3,oneof"`
}

func (*SendLogsRequest_LogEntry) isSendLogsRequest_Request() {}

// Message to encapsulate setting the log level.
type SetLogLevel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The log level to be set in the operator.
	Level LogLevel `protobuf:"varint,1,opt,name=level,proto3,enum=illumio.cloud.k8scluster.v1.LogLevel" json:"level,omitempty"`
}

func (x *SetLogLevel) Reset() {
	*x = SetLogLevel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetLogLevel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetLogLevel) ProtoMessage() {}

func (x *SetLogLevel) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetLogLevel.ProtoReflect.Descriptor instead.
func (*SetLogLevel) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{9}
}

func (x *SetLogLevel) GetLevel() LogLevel {
	if x != nil {
		return x.Level
	}
	return LogLevel_LOG_LEVEL_UNSPECIFIED
}

// Message to encapsulate the response for sending logs.
type SendLogsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*SendLogsResponse_SetLogLevel
	Response isSendLogsResponse_Response `protobuf_oneof:"response"`
}

func (x *SendLogsResponse) Reset() {
	*x = SendLogsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendLogsResponse) ProtoMessage() {}

func (x *SendLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendLogsResponse.ProtoReflect.Descriptor instead.
func (*SendLogsResponse) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP(), []int{10}
}

func (m *SendLogsResponse) GetResponse() isSendLogsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *SendLogsResponse) GetSetLogLevel() *SetLogLevel {
	if x, ok := x.GetResponse().(*SendLogsResponse_SetLogLevel); ok {
		return x.SetLogLevel
	}
	return nil
}

type isSendLogsResponse_Response interface {
	isSendLogsResponse_Response()
}

type SendLogsResponse_SetLogLevel struct {
	// set_log_level sets the operator's log level to the given level.
	SetLogLevel *SetLogLevel `protobuf:"bytes,1,opt,name=set_log_level,json=setLogLevel,proto3,oneof"`
}

func (*SendLogsResponse_SetLogLevel) isSendLogsResponse_Response() {}

var File_illumio_cloud_k8scluster_v1_resource_config_proto protoreflect.FileDescriptor

var file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDesc = []byte{
	0x0a, 0x31, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x2f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x1b, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31,
	0x1a, 0x1f, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75,
	0x66, 0x2f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x22, 0x8a, 0x05, 0x0a, 0x18, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x68,
	0x0a, 0x0b, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x46, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65,
	0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x41, 0x6e, 0x6e, 0x6f, 0x74,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x0b, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x49, 0x0a, 0x12, 0x63, 0x72, 0x65, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70,
	0x52, 0x11, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x12, 0x59, 0x0a, 0x06, 0x6c, 0x61, 0x62, 0x65, 0x6c,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x41, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69,
	0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x2e, 0x4c,
	0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x06, 0x6c, 0x61, 0x62, 0x65,
	0x6c, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73,
	0x70, 0x61, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x10, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x72, 0x65,
	0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x18, 0x07, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35,
	0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b,
	0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x52, 0x0f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x52, 0x65, 0x66, 0x65,
	0x72, 0x65, 0x6e, 0x63, 0x65, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72,
	0x63, 0x65, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0f, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x75, 0x69, 0x64, 0x1a, 0x3e, 0x0a, 0x10, 0x41, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0x39, 0x0a, 0x0b, 0x4c, 0x61, 0x62, 0x65, 0x6c, 0x73, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xc7,
	0x01, 0x0a, 0x18, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x77, 0x6e,
	0x65, 0x72, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x61,
	0x70, 0x69, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x61, 0x70, 0x69, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x30, 0x0a, 0x14,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x5f, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x5f, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x4f, 0x77, 0x6e, 0x65, 0x72, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x12, 0x12,
	0x0a, 0x04, 0x6b, 0x69, 0x6e, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6b, 0x69,
	0x6e, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x06, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x22, 0x87, 0x01, 0x0a, 0x19, 0x4b, 0x75, 0x62,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x10, 0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64, 0x12, 0x2d, 0x0a, 0x12, 0x6b, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x11, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a, 0x10, 0x6f, 0x70, 0x65, 0x72, 0x61,
	0x74, 0x6f, 0x72, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0f, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f, 0x72, 0x56, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x22, 0xf4, 0x03, 0x0a, 0x1e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x63, 0x0a, 0x10, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x36, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e,
	0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75,
	0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x43, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x4d,
	0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0f, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x12, 0x64, 0x0a, 0x11, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e,
	0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62,
	0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x10,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x12, 0x7f, 0x0a, 0x1a, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x73, 0x6e, 0x61,
	0x70, 0x73, 0x68, 0x6f, 0x74, 0x5f, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x3f, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63,
	0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e,
	0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x43, 0x6f, 0x6d,
	0x70, 0x6c, 0x65, 0x74, 0x65, 0x48, 0x00, 0x52, 0x18, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74,
	0x65, 0x12, 0x7b, 0x0a, 0x1c, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x5f, 0x6d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x37, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69,
	0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74,
	0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x48, 0x00, 0x52, 0x1a, 0x6b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x42, 0x09,
	0x0a, 0x07, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x24, 0x0a, 0x22, 0x4b, 0x75, 0x62,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x53,
	0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x65, 0x74, 0x65, 0x22,
	0x21, 0x0a, 0x1f, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0xce, 0x02, 0x0a, 0x1a, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65,
	0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x4d, 0x75, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x60, 0x0a, 0x0f, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x69, 0x6c, 0x6c,
	0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65,
	0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74,
	0x61, 0x48, 0x00, 0x52, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x5f, 0x72, 0x65,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35, 0x2e, 0x69,
	0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62, 0x65, 0x72,
	0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74, 0x61, 0x64,
	0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0e, 0x75, 0x70, 0x64, 0x61, 0x74, 0x65, 0x52, 0x65, 0x73,
	0x6f, 0x75, 0x72, 0x63, 0x65, 0x12, 0x60, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x35,
	0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b,
	0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x75, 0x62,
	0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x4f, 0x62, 0x6a, 0x65, 0x63, 0x74, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x48, 0x00, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x42, 0x0a, 0x0a, 0x08, 0x6d, 0x75, 0x74, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x32, 0xb2, 0x01, 0x0a, 0x15, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74,
	0x65, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x98, 0x01,
	0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73,
	0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x12, 0x3b, 0x2e, 0x69, 0x6c, 0x6c, 0x75,
	0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75,
	0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x75, 0x62, 0x65,
	0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x3c, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f,
	0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65,
	0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65,
	0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x97, 0x02, 0x0a, 0x1f, 0x63, 0x6f, 0x6d,
	0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b,
	0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e,
	0x64, 0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01,
	0x12, 0x6b, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67, 0x73, 0x12, 0x2c, 0x2e, 0x69,
	0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c,
	0x6f, 0x67, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2d, 0x2e, 0x69, 0x6c, 0x6c,
	0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c,
	0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x4c, 0x6f, 0x67,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x97, 0x02,
	0x0a, 0x1f, 0x63, 0x6f, 0x6d, 0x2e, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x63, 0x6c,
	0x6f, 0x75, 0x64, 0x2e, 0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x76,
	0x31, 0x42, 0x13, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x50, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2f, 0x63, 0x6c, 0x6f,
	0x75, 0x64, 0x73, 0x65, 0x63, 0x75, 0x72, 0x65, 0x2d, 0x6f, 0x70, 0x65, 0x72, 0x61, 0x74, 0x6f,
	0x72, 0x2f, 0x69, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2f, 0x63, 0x6c, 0x6f, 0x75, 0x64, 0x2f,
	0x6b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2f, 0x76, 0x31, 0x3b, 0x6b, 0x38,
	0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x76, 0x31, 0xa2, 0x02, 0x03, 0x49, 0x43, 0x4b,
	0xaa, 0x02, 0x1b, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x2e, 0x43, 0x6c, 0x6f, 0x75, 0x64,
	0x2e, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x2e, 0x56, 0x31, 0xca, 0x02,
	0x1b, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x5c, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x5c, 0x4b,
	0x38, 0x73, 0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5c, 0x56, 0x31, 0xe2, 0x02, 0x27, 0x49,
	0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f, 0x5c, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x5c, 0x4b, 0x38, 0x73,
	0x63, 0x6c, 0x75, 0x73, 0x74, 0x65, 0x72, 0x5c, 0x56, 0x31, 0x5c, 0x47, 0x50, 0x42, 0x4d, 0x65,
	0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x1e, 0x49, 0x6c, 0x6c, 0x75, 0x6d, 0x69, 0x6f,
	0x3a, 0x3a, 0x43, 0x6c, 0x6f, 0x75, 0x64, 0x3a, 0x3a, 0x4b, 0x38, 0x73, 0x63, 0x6c, 0x75, 0x73,
	0x74, 0x65, 0x72, 0x3a, 0x3a, 0x56, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescOnce sync.Once
	file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescData = file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDesc
)

func file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescGZIP() []byte {
	file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescOnce.Do(func() {
		file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescData = protoimpl.X.CompressGZIP(file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescData)
	})
	return file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDescData
}

var file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_illumio_cloud_k8scluster_v1_resource_config_proto_goTypes = []any{
	(TrafficDirection)(0),                      // 0: illumio.cloud.k8scluster.v1.TrafficDirection
	(Verdict)(0),                               // 1: illumio.cloud.k8scluster.v1.Verdict
	(IPVersion)(0),                             // 2: illumio.cloud.k8scluster.v1.IPVersion
	(*KubernetesObjectMetadata)(nil),           // 3: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata
	(*KubernetesOwnerReference)(nil),           // 4: illumio.cloud.k8scluster.v1.KubernetesOwnerReference
	(*KubernetesClusterMetadata)(nil),          // 5: illumio.cloud.k8scluster.v1.KubernetesClusterMetadata
	(*SendKubernetesResourcesRequest)(nil),     // 6: illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest
	(*KubernetesResourceSnapshotComplete)(nil), // 7: illumio.cloud.k8scluster.v1.KubernetesResourceSnapshotComplete
	(*SendKubernetesResourcesResponse)(nil),    // 8: illumio.cloud.k8scluster.v1.SendKubernetesResourcesResponse
	(*KubernetesResourceMutation)(nil),         // 9: illumio.cloud.k8scluster.v1.KubernetesResourceMutation
	(*CiliumFlow)(nil),                         // 10: illumio.cloud.k8scluster.v1.CiliumFlow
	(*IP)(nil),                                 // 11: illumio.cloud.k8scluster.v1.IP
	(*Layer4)(nil),                             // 12: illumio.cloud.k8scluster.v1.Layer4
	(*TCP)(nil),                                // 13: illumio.cloud.k8scluster.v1.TCP
	(*TCPFlags)(nil),                           // 14: illumio.cloud.k8scluster.v1.TCPFlags
	(*UDP)(nil),                                // 15: illumio.cloud.k8scluster.v1.UDP
	(*SCTP)(nil),                               // 16: illumio.cloud.k8scluster.v1.SCTP
	(*ICMPv4)(nil),                             // 17: illumio.cloud.k8scluster.v1.ICMPv4
	(*ICMPv6)(nil),                             // 18: illumio.cloud.k8scluster.v1.ICMPv6
	(*CiliumEventType)(nil),                    // 19: illumio.cloud.k8scluster.v1.CiliumEventType
	(*Endpoint)(nil),                           // 20: illumio.cloud.k8scluster.v1.Endpoint
	(*NetworkInterface)(nil),                   // 21: illumio.cloud.k8scluster.v1.NetworkInterface
	(*Workload)(nil),                           // 22: illumio.cloud.k8scluster.v1.Workload
	(*Policy)(nil),                             // 23: illumio.cloud.k8scluster.v1.Policy
	(*SendKubernetesNetworkFlowsRequest)(nil),  // 24: illumio.cloud.k8scluster.v1.SendKubernetesNetworkFlowsRequest
	(*SendKubernetesNetworkFlowsResponse)(nil), // 25: illumio.cloud.k8scluster.v1.SendKubernetesNetworkFlowsResponse
	nil,                           // 26: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.AnnotationsEntry
	nil,                           // 27: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.LabelsEntry
	(*timestamppb.Timestamp)(nil), // 28: google.protobuf.Timestamp
	(LogLevel)(0),                              // 0: illumio.cloud.k8scluster.v1.LogLevel
	(*KubernetesObjectMetadata)(nil),           // 1: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata
	(*KubernetesOwnerReference)(nil),           // 2: illumio.cloud.k8scluster.v1.KubernetesOwnerReference
	(*KubernetesClusterMetadata)(nil),          // 3: illumio.cloud.k8scluster.v1.KubernetesClusterMetadata
	(*SendKubernetesResourcesRequest)(nil),     // 4: illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest
	(*KubernetesResourceSnapshotComplete)(nil), // 5: illumio.cloud.k8scluster.v1.KubernetesResourceSnapshotComplete
	(*SendKubernetesResourcesResponse)(nil),    // 6: illumio.cloud.k8scluster.v1.SendKubernetesResourcesResponse
	(*KubernetesResourceMutation)(nil),         // 7: illumio.cloud.k8scluster.v1.KubernetesResourceMutation
	(*LogEntry)(nil),                           // 8: illumio.cloud.k8scluster.v1.LogEntry
	(*SendLogsRequest)(nil),                    // 9: illumio.cloud.k8scluster.v1.SendLogsRequest
	(*SetLogLevel)(nil),                        // 10: illumio.cloud.k8scluster.v1.SetLogLevel
	(*SendLogsResponse)(nil),                   // 11: illumio.cloud.k8scluster.v1.SendLogsResponse
	nil,                                        // 12: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.AnnotationsEntry
	nil,                                        // 13: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.LabelsEntry
	(*timestamppb.Timestamp)(nil),              // 14: google.protobuf.Timestamp
}
var file_illumio_cloud_k8scluster_v1_resource_config_proto_depIdxs = []int32{
	7,  // 0: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.annotations:type_name -> illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.AnnotationsEntry
	9,  // 1: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.creation_timestamp:type_name -> google.protobuf.Timestamp
	8,  // 2: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.labels:type_name -> illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.LabelsEntry
	1,  // 3: illumio.cloud.k8scluster.v1.KubernetesObjectMetadata.owner_references:type_name -> illumio.cloud.k8scluster.v1.KubernetesOwnerReference
	2,  // 4: illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest.cluster_metadata:type_name -> illumio.cloud.k8scluster.v1.KubernetesClusterMetadata
	0,  // 5: illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest.resource_metadata:type_name -> illumio.cloud.k8scluster.v1.KubernetesObjectMetadata
	4,  // 6: illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest.resource_snapshot_complete:type_name -> illumio.cloud.k8scluster.v1.KubernetesResourceSnapshotComplete
	6,  // 7: illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest.kubernetes_resource_mutation:type_name -> illumio.cloud.k8scluster.v1.KubernetesResourceMutation
	0,  // 8: illumio.cloud.k8scluster.v1.KubernetesResourceMutation.create_resource:type_name -> illumio.cloud.k8scluster.v1.KubernetesObjectMetadata
	0,  // 9: illumio.cloud.k8scluster.v1.KubernetesResourceMutation.update_resource:type_name -> illumio.cloud.k8scluster.v1.KubernetesObjectMetadata
	0,  // 10: illumio.cloud.k8scluster.v1.KubernetesResourceMutation.delete_resource:type_name -> illumio.cloud.k8scluster.v1.KubernetesObjectMetadata
	3,  // 11: illumio.cloud.k8scluster.v1.KubernetesInfoService.SendKubernetesResources:input_type -> illumio.cloud.k8scluster.v1.SendKubernetesResourcesRequest
	5,  // 12: illumio.cloud.k8scluster.v1.KubernetesInfoService.SendKubernetesResources:output_type -> illumio.cloud.k8scluster.v1.SendKubernetesResourcesResponse
	12, // [12:13] is the sub-list for method output_type
	11, // [11:12] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_illumio_cloud_k8scluster_v1_resource_config_proto_init() }
func file_illumio_cloud_k8scluster_v1_resource_config_proto_init() {
	if File_illumio_cloud_k8scluster_v1_resource_config_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*KubernetesObjectMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*KubernetesOwnerReference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*KubernetesClusterMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*SendKubernetesResourcesRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*KubernetesResourceSnapshotComplete); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SendKubernetesResourcesResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*KubernetesResourceMutation); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[3].OneofWrappers = []any{
		(*SendKubernetesResourcesRequest_ClusterMetadata)(nil),
		(*SendKubernetesResourcesRequest_ResourceMetadata)(nil),
		(*SendKubernetesResourcesRequest_ResourceSnapshotComplete)(nil),
		(*SendKubernetesResourcesRequest_KubernetesResourceMutation)(nil),
	}
	file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes[6].OneofWrappers = []any{
		(*KubernetesResourceMutation_CreateResource)(nil),
		(*KubernetesResourceMutation_UpdateResource)(nil),
		(*KubernetesResourceMutation_DeleteResource)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDesc,
			NumEnums:      3,
			NumMessages:   25,
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_illumio_cloud_k8scluster_v1_resource_config_proto_goTypes,
		DependencyIndexes: file_illumio_cloud_k8scluster_v1_resource_config_proto_depIdxs,
		EnumInfos:         file_illumio_cloud_k8scluster_v1_resource_config_proto_enumTypes,
		MessageInfos:      file_illumio_cloud_k8scluster_v1_resource_config_proto_msgTypes,
	}.Build()
	File_illumio_cloud_k8scluster_v1_resource_config_proto = out.File
	file_illumio_cloud_k8scluster_v1_resource_config_proto_rawDesc = nil
	file_illumio_cloud_k8scluster_v1_resource_config_proto_goTypes = nil
	file_illumio_cloud_k8scluster_v1_resource_config_proto_depIdxs = nil
}
