// Copyright 2024 Illumio, Inc. All Rights Reserved.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: illumio/cloud/goldmane/v1/goldmane.proto

package goldmanev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StreamRequest initiates a flow stream from Goldmane
type StreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamRequest) Reset() {
	*x = StreamRequest{}
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamRequest) ProtoMessage() {}

func (x *StreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamRequest.ProtoReflect.Descriptor instead.
func (*StreamRequest) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP(), []int{0}
}

// StreamResponse contains a single flow from Goldmane
type StreamResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Flow          *Flow                  `protobuf:"bytes,2,opt,name=flow,proto3" json:"flow,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamResponse) Reset() {
	*x = StreamResponse{}
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamResponse) ProtoMessage() {}

func (x *StreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamResponse.ProtoReflect.Descriptor instead.
func (*StreamResponse) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP(), []int{1}
}

func (x *StreamResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StreamResponse) GetFlow() *Flow {
	if x != nil {
		return x.Flow
	}
	return nil
}

// Flow represents a network flow in Goldmane's format
type Flow struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Key                     *FlowKey               `protobuf:"bytes,1,opt,name=Key,proto3" json:"Key,omitempty"`
	StartTime               string                 `protobuf:"bytes,2,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime                 string                 `protobuf:"bytes,3,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	SourceLabels            []string               `protobuf:"bytes,4,rep,name=source_labels,json=sourceLabels,proto3" json:"source_labels,omitempty"`
	DestLabels              []string               `protobuf:"bytes,5,rep,name=dest_labels,json=destLabels,proto3" json:"dest_labels,omitempty"`
	PacketsIn               string                 `protobuf:"bytes,6,opt,name=packets_in,json=packetsIn,proto3" json:"packets_in,omitempty"`
	PacketsOut              string                 `protobuf:"bytes,7,opt,name=packets_out,json=packetsOut,proto3" json:"packets_out,omitempty"`
	BytesIn                 string                 `protobuf:"bytes,8,opt,name=bytes_in,json=bytesIn,proto3" json:"bytes_in,omitempty"`
	BytesOut                string                 `protobuf:"bytes,9,opt,name=bytes_out,json=bytesOut,proto3" json:"bytes_out,omitempty"`
	NumConnectionsStarted   string                 `protobuf:"bytes,10,opt,name=num_connections_started,json=numConnectionsStarted,proto3" json:"num_connections_started,omitempty"`
	NumConnectionsCompleted string                 `protobuf:"bytes,11,opt,name=num_connections_completed,json=numConnectionsCompleted,proto3" json:"num_connections_completed,omitempty"`
	NumConnectionsLive      string                 `protobuf:"bytes,12,opt,name=num_connections_live,json=numConnectionsLive,proto3" json:"num_connections_live,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *Flow) Reset() {
	*x = Flow{}
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Flow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Flow) ProtoMessage() {}

func (x *Flow) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Flow.ProtoReflect.Descriptor instead.
func (*Flow) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP(), []int{2}
}

func (x *Flow) GetKey() *FlowKey {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Flow) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *Flow) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *Flow) GetSourceLabels() []string {
	if x != nil {
		return x.SourceLabels
	}
	return nil
}

func (x *Flow) GetDestLabels() []string {
	if x != nil {
		return x.DestLabels
	}
	return nil
}

func (x *Flow) GetPacketsIn() string {
	if x != nil {
		return x.PacketsIn
	}
	return ""
}

func (x *Flow) GetPacketsOut() string {
	if x != nil {
		return x.PacketsOut
	}
	return ""
}

func (x *Flow) GetBytesIn() string {
	if x != nil {
		return x.BytesIn
	}
	return ""
}

func (x *Flow) GetBytesOut() string {
	if x != nil {
		return x.BytesOut
	}
	return ""
}

func (x *Flow) GetNumConnectionsStarted() string {
	if x != nil {
		return x.NumConnectionsStarted
	}
	return ""
}

func (x *Flow) GetNumConnectionsCompleted() string {
	if x != nil {
		return x.NumConnectionsCompleted
	}
	return ""
}

func (x *Flow) GetNumConnectionsLive() string {
	if x != nil {
		return x.NumConnectionsLive
	}
	return ""
}

// FlowKey uniquely identifies a flow
type FlowKey struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	SourceName           string                 `protobuf:"bytes,1,opt,name=source_name,json=sourceName,proto3" json:"source_name,omitempty"`
	SourceNamespace      string                 `protobuf:"bytes,2,opt,name=source_namespace,json=sourceNamespace,proto3" json:"source_namespace,omitempty"`
	SourceType           string                 `protobuf:"bytes,3,opt,name=source_type,json=sourceType,proto3" json:"source_type,omitempty"`
	DestName             string                 `protobuf:"bytes,4,opt,name=dest_name,json=destName,proto3" json:"dest_name,omitempty"`
	DestNamespace        string                 `protobuf:"bytes,5,opt,name=dest_namespace,json=destNamespace,proto3" json:"dest_namespace,omitempty"`
	DestType             string                 `protobuf:"bytes,6,opt,name=dest_type,json=destType,proto3" json:"dest_type,omitempty"`
	DestPort             string                 `protobuf:"bytes,7,opt,name=dest_port,json=destPort,proto3" json:"dest_port,omitempty"`
	DestServiceName      string                 `protobuf:"bytes,8,opt,name=dest_service_name,json=destServiceName,proto3" json:"dest_service_name,omitempty"`
	DestServiceNamespace string                 `protobuf:"bytes,9,opt,name=dest_service_namespace,json=destServiceNamespace,proto3" json:"dest_service_namespace,omitempty"`
	DestServicePortName  string                 `protobuf:"bytes,10,opt,name=dest_service_port_name,json=destServicePortName,proto3" json:"dest_service_port_name,omitempty"`
	DestServicePort      string                 `protobuf:"bytes,11,opt,name=dest_service_port,json=destServicePort,proto3" json:"dest_service_port,omitempty"`
	Proto                string                 `protobuf:"bytes,12,opt,name=proto,proto3" json:"proto,omitempty"`
	Reporter             string                 `protobuf:"bytes,13,opt,name=reporter,proto3" json:"reporter,omitempty"`
	Action               string                 `protobuf:"bytes,14,opt,name=action,proto3" json:"action,omitempty"`
	Policies             *Policies              `protobuf:"bytes,15,opt,name=policies,proto3" json:"policies,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *FlowKey) Reset() {
	*x = FlowKey{}
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlowKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlowKey) ProtoMessage() {}

func (x *FlowKey) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlowKey.ProtoReflect.Descriptor instead.
func (*FlowKey) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP(), []int{3}
}

func (x *FlowKey) GetSourceName() string {
	if x != nil {
		return x.SourceName
	}
	return ""
}

func (x *FlowKey) GetSourceNamespace() string {
	if x != nil {
		return x.SourceNamespace
	}
	return ""
}

func (x *FlowKey) GetSourceType() string {
	if x != nil {
		return x.SourceType
	}
	return ""
}

func (x *FlowKey) GetDestName() string {
	if x != nil {
		return x.DestName
	}
	return ""
}

func (x *FlowKey) GetDestNamespace() string {
	if x != nil {
		return x.DestNamespace
	}
	return ""
}

func (x *FlowKey) GetDestType() string {
	if x != nil {
		return x.DestType
	}
	return ""
}

func (x *FlowKey) GetDestPort() string {
	if x != nil {
		return x.DestPort
	}
	return ""
}

func (x *FlowKey) GetDestServiceName() string {
	if x != nil {
		return x.DestServiceName
	}
	return ""
}

func (x *FlowKey) GetDestServiceNamespace() string {
	if x != nil {
		return x.DestServiceNamespace
	}
	return ""
}

func (x *FlowKey) GetDestServicePortName() string {
	if x != nil {
		return x.DestServicePortName
	}
	return ""
}

func (x *FlowKey) GetDestServicePort() string {
	if x != nil {
		return x.DestServicePort
	}
	return ""
}

func (x *FlowKey) GetProto() string {
	if x != nil {
		return x.Proto
	}
	return ""
}

func (x *FlowKey) GetReporter() string {
	if x != nil {
		return x.Reporter
	}
	return ""
}

func (x *FlowKey) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *FlowKey) GetPolicies() *Policies {
	if x != nil {
		return x.Policies
	}
	return nil
}

// Policies contains enforced and pending policies for a flow
type Policies struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EnforcedPolicies []*Policy              `protobuf:"bytes,1,rep,name=enforced_policies,json=enforcedPolicies,proto3" json:"enforced_policies,omitempty"`
	PendingPolicies  []*Policy              `protobuf:"bytes,2,rep,name=pending_policies,json=pendingPolicies,proto3" json:"pending_policies,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Policies) Reset() {
	*x = Policies{}
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policies) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policies) ProtoMessage() {}

func (x *Policies) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policies.ProtoReflect.Descriptor instead.
func (*Policies) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP(), []int{4}
}

func (x *Policies) GetEnforcedPolicies() []*Policy {
	if x != nil {
		return x.EnforcedPolicies
	}
	return nil
}

func (x *Policies) GetPendingPolicies() []*Policy {
	if x != nil {
		return x.PendingPolicies
	}
	return nil
}

// Policy represents a single Calico network policy
type Policy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Kind          string                 `protobuf:"bytes,1,opt,name=kind,proto3" json:"kind,omitempty"`
	Namespace     string                 `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Tier          string                 `protobuf:"bytes,4,opt,name=tier,proto3" json:"tier,omitempty"`
	Action        string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Policy) Reset() {
	*x = Policy{}
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Policy) ProtoMessage() {}

func (x *Policy) ProtoReflect() protoreflect.Message {
	mi := &file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Policy.ProtoReflect.Descriptor instead.
func (*Policy) Descriptor() ([]byte, []int) {
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP(), []int{5}
}

func (x *Policy) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Policy) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Policy) GetTier() string {
	if x != nil {
		return x.Tier
	}
	return ""
}

func (x *Policy) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

var File_illumio_cloud_goldmane_v1_goldmane_proto protoreflect.FileDescriptor

const file_illumio_cloud_goldmane_v1_goldmane_proto_rawDesc = "" +
	"\n" +
	"(illumio/cloud/goldmane/v1/goldmane.proto\x12\x19illumio.cloud.goldmane.v1\"\x0f\n" +
	"\rStreamRequest\"U\n" +
	"\x0eStreamResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x123\n" +
	"\x04flow\x18\x02 \x01(\v2\x1f.illumio.cloud.goldmane.v1.FlowR\x04flow\"\xda\x03\n" +
	"\x04Flow\x124\n" +
	"\x03Key\x18\x01 \x01(\v2\".illumio.cloud.goldmane.v1.FlowKeyR\x03Key\x12\x1d\n" +
	"\n" +
	"start_time\x18\x02 \x01(\tR\tstartTime\x12\x19\n" +
	"\bend_time\x18\x03 \x01(\tR\aendTime\x12#\n" +
	"\rsource_labels\x18\x04 \x03(\tR\fsourceLabels\x12\x1f\n" +
	"\vdest_labels\x18\x05 \x03(\tR\n" +
	"destLabels\x12\x1d\n" +
	"\n" +
	"packets_in\x18\x06 \x01(\tR\tpacketsIn\x12\x1f\n" +
	"\vpackets_out\x18\a \x01(\tR\n" +
	"packetsOut\x12\x19\n" +
	"\bbytes_in\x18\b \x01(\tR\abytesIn\x12\x1b\n" +
	"\tbytes_out\x18\t \x01(\tR\bbytesOut\x126\n" +
	"\x17num_connections_started\x18\n" +
	" \x01(\tR\x15numConnectionsStarted\x12:\n" +
	"\x19num_connections_completed\x18\v \x01(\tR\x17numConnectionsCompleted\x120\n" +
	"\x14num_connections_live\x18\f \x01(\tR\x12numConnectionsLive\"\xc2\x04\n" +
	"\aFlowKey\x12\x1f\n" +
	"\vsource_name\x18\x01 \x01(\tR\n" +
	"sourceName\x12)\n" +
	"\x10source_namespace\x18\x02 \x01(\tR\x0fsourceNamespace\x12\x1f\n" +
	"\vsource_type\x18\x03 \x01(\tR\n" +
	"sourceType\x12\x1b\n" +
	"\tdest_name\x18\x04 \x01(\tR\bdestName\x12%\n" +
	"\x0edest_namespace\x18\x05 \x01(\tR\rdestNamespace\x12\x1b\n" +
	"\tdest_type\x18\x06 \x01(\tR\bdestType\x12\x1b\n" +
	"\tdest_port\x18\a \x01(\tR\bdestPort\x12*\n" +
	"\x11dest_service_name\x18\b \x01(\tR\x0fdestServiceName\x124\n" +
	"\x16dest_service_namespace\x18\t \x01(\tR\x14destServiceNamespace\x123\n" +
	"\x16dest_service_port_name\x18\n" +
	" \x01(\tR\x13destServicePortName\x12*\n" +
	"\x11dest_service_port\x18\v \x01(\tR\x0fdestServicePort\x12\x14\n" +
	"\x05proto\x18\f \x01(\tR\x05proto\x12\x1a\n" +
	"\breporter\x18\r \x01(\tR\breporter\x12\x16\n" +
	"\x06action\x18\x0e \x01(\tR\x06action\x12?\n" +
	"\bpolicies\x18\x0f \x01(\v2#.illumio.cloud.goldmane.v1.PoliciesR\bpolicies\"\xa8\x01\n" +
	"\bPolicies\x12N\n" +
	"\x11enforced_policies\x18\x01 \x03(\v2!.illumio.cloud.goldmane.v1.PolicyR\x10enforcedPolicies\x12L\n" +
	"\x10pending_policies\x18\x02 \x03(\v2!.illumio.cloud.goldmane.v1.PolicyR\x0fpendingPolicies\"z\n" +
	"\x06Policy\x12\x12\n" +
	"\x04kind\x18\x01 \x01(\tR\x04kind\x12\x1c\n" +
	"\tnamespace\x18\x02 \x01(\tR\tnamespace\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x12\n" +
	"\x04tier\x18\x04 \x01(\tR\x04tier\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action2h\n" +
	"\x05Flows\x12_\n" +
	"\x06Stream\x12(.illumio.cloud.goldmane.v1.StreamRequest\x1a).illumio.cloud.goldmane.v1.StreamResponse0\x01B\x83\x02\n" +
	"\x1dcom.illumio.cloud.goldmane.v1B\rGoldmaneProtoP\x01ZLgithub.com/illumio/cloudsecure-operator/illumio/cloud/goldmane/v1;goldmanev1\xa2\x02\x03ICG\xaa\x02\x19Illumio.Cloud.Goldmane.V1\xca\x02\x19Illumio\\Cloud\\Goldmane\\V1\xe2\x02%Illumio\\Cloud\\Goldmane\\V1\\GPBMetadata\xea\x02\x1cIllumio::Cloud::Goldmane::V1b\x06proto3"

var (
	file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescOnce sync.Once
	file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescData []byte
)

func file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescGZIP() []byte {
	file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescOnce.Do(func() {
		file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_illumio_cloud_goldmane_v1_goldmane_proto_rawDesc), len(file_illumio_cloud_goldmane_v1_goldmane_proto_rawDesc)))
	})
	return file_illumio_cloud_goldmane_v1_goldmane_proto_rawDescData
}

var file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_illumio_cloud_goldmane_v1_goldmane_proto_goTypes = []any{
	(*StreamRequest)(nil),  // 0: illumio.cloud.goldmane.v1.StreamRequest
	(*StreamResponse)(nil), // 1: illumio.cloud.goldmane.v1.StreamResponse
	(*Flow)(nil),           // 2: illumio.cloud.goldmane.v1.Flow
	(*FlowKey)(nil),        // 3: illumio.cloud.goldmane.v1.FlowKey
	(*Policies)(nil),       // 4: illumio.cloud.goldmane.v1.Policies
	(*Policy)(nil),         // 5: illumio.cloud.goldmane.v1.Policy
}
var file_illumio_cloud_goldmane_v1_goldmane_proto_depIdxs = []int32{
	2, // 0: illumio.cloud.goldmane.v1.StreamResponse.flow:type_name -> illumio.cloud.goldmane.v1.Flow
	3, // 1: illumio.cloud.goldmane.v1.Flow.Key:type_name -> illumio.cloud.goldmane.v1.FlowKey
	4, // 2: illumio.cloud.goldmane.v1.FlowKey.policies:type_name -> illumio.cloud.goldmane.v1.Policies
	5, // 3: illumio.cloud.goldmane.v1.Policies.enforced_policies:type_name -> illumio.cloud.goldmane.v1.Policy
	5, // 4: illumio.cloud.goldmane.v1.Policies.pending_policies:type_name -> illumio.cloud.goldmane.v1.Policy
	0, // 5: illumio.cloud.goldmane.v1.Flows.Stream:input_type -> illumio.cloud.goldmane.v1.StreamRequest
	1, // 6: illumio.cloud.goldmane.v1.Flows.Stream:output_type -> illumio.cloud.goldmane.v1.StreamResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_illumio_cloud_goldmane_v1_goldmane_proto_init() }
func file_illumio_cloud_goldmane_v1_goldmane_proto_init() {
	if File_illumio_cloud_goldmane_v1_goldmane_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_illumio_cloud_goldmane_v1_goldmane_proto_rawDesc), len(file_illumio_cloud_goldmane_v1_goldmane_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_illumio_cloud_goldmane_v1_goldmane_proto_goTypes,
		DependencyIndexes: file_illumio_cloud_goldmane_v1_goldmane_proto_depIdxs,
		MessageInfos:      file_illumio_cloud_goldmane_v1_goldmane_proto_msgTypes,
	}.Build()
	File_illumio_cloud_goldmane_v1_goldmane_proto = out.File
	file_illumio_cloud_goldmane_v1_goldmane_proto_goTypes = nil
	file_illumio_cloud_goldmane_v1_goldmane_proto_depIdxs = nil
}
