// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.29.3
// source: api/illumio/cloud/goldmane/v1/goldmane.proto

package goldmanepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// FlowsClient is the client API for Flows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FlowsClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Flows_StreamClient, error)
}

type flowsClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowsClient(cc grpc.ClientConnInterface) FlowsClient {
	return &flowsClient{cc}
}

func (c *flowsClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (Flows_StreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &Flows_ServiceDesc.Streams[0], "/goldmane.Flows/Stream", opts...)
	if err != nil {
		return nil, err
	}
	x := &flowsStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type Flows_StreamClient interface {
	Recv() (*StreamResponse, error)
	grpc.ClientStream
}

type flowsStreamClient struct {
	grpc.ClientStream
}

func (x *flowsStreamClient) Recv() (*StreamResponse, error) {
	m := new(StreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FlowsServer is the server API for Flows service.
// All implementations must embed UnimplementedFlowsServer
// for forward compatibility
type FlowsServer interface {
	Stream(*StreamRequest, Flows_StreamServer) error
	mustEmbedUnimplementedFlowsServer()
}

// UnimplementedFlowsServer must be embedded to have forward compatible implementations.
type UnimplementedFlowsServer struct {
}

func (UnimplementedFlowsServer) Stream(*StreamRequest, Flows_StreamServer) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFlowsServer) mustEmbedUnimplementedFlowsServer() {}

// UnsafeFlowsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowsServer will
// result in compilation errors.
type UnsafeFlowsServer interface {
	mustEmbedUnimplementedFlowsServer()
}

func RegisterFlowsServer(s grpc.ServiceRegistrar, srv FlowsServer) {
	s.RegisterService(&Flows_ServiceDesc, srv)
}

func _Flows_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowsServer).Stream(m, &flowsStreamServer{stream})
}

type Flows_StreamServer interface {
	Send(*StreamResponse) error
	grpc.ServerStream
}

type flowsStreamServer struct {
	grpc.ServerStream
}

func (x *flowsStreamServer) Send(m *StreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// Flows_ServiceDesc is the grpc.ServiceDesc for Flows service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flows_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "goldmane.Flows",
	HandlerType: (*FlowsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Flows_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "api/illumio/cloud/goldmane/v1/goldmane.proto",
}
