// Copyright 2024 Illumio, Inc. All Rights Reserved.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: illumio/cloud/goldmane/v1/goldmane.proto

package goldmanev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Flows_Stream_FullMethodName = "/illumio.cloud.goldmane.v1.Flows/Stream"
)

// FlowsClient is the client API for Flows service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Flows service provides network flow streaming from Goldmane
type FlowsClient interface {
	Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error)
}

type flowsClient struct {
	cc grpc.ClientConnInterface
}

func NewFlowsClient(cc grpc.ClientConnInterface) FlowsClient {
	return &flowsClient{cc}
}

func (c *flowsClient) Stream(ctx context.Context, in *StreamRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StreamResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Flows_ServiceDesc.Streams[0], Flows_Stream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StreamRequest, StreamResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Flows_StreamClient = grpc.ServerStreamingClient[StreamResponse]

// FlowsServer is the server API for Flows service.
// All implementations must embed UnimplementedFlowsServer
// for forward compatibility.
//
// Flows service provides network flow streaming from Goldmane
type FlowsServer interface {
	Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error
	mustEmbedUnimplementedFlowsServer()
}

// UnimplementedFlowsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFlowsServer struct{}

func (UnimplementedFlowsServer) Stream(*StreamRequest, grpc.ServerStreamingServer[StreamResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Stream not implemented")
}
func (UnimplementedFlowsServer) mustEmbedUnimplementedFlowsServer() {}
func (UnimplementedFlowsServer) testEmbeddedByValue()               {}

// UnsafeFlowsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FlowsServer will
// result in compilation errors.
type UnsafeFlowsServer interface {
	mustEmbedUnimplementedFlowsServer()
}

func RegisterFlowsServer(s grpc.ServiceRegistrar, srv FlowsServer) {
	// If the following call pancis, it indicates UnimplementedFlowsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Flows_ServiceDesc, srv)
}

func _Flows_Stream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(FlowsServer).Stream(m, &grpc.GenericServerStream[StreamRequest, StreamResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Flows_StreamServer = grpc.ServerStreamingServer[StreamResponse]

// Flows_ServiceDesc is the grpc.ServiceDesc for Flows service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Flows_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "illumio.cloud.goldmane.v1.Flows",
	HandlerType: (*FlowsServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Stream",
			Handler:       _Flows_Stream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "illumio/cloud/goldmane/v1/goldmane.proto",
}
