# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-operator.fullname" . }}
  namespace: {{ .Values.defaultNamespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloud-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cloud-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 65532
      priorityClassName: {{ .Values.priorityClassName }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
          {{- range .Values.imagePullSecrets }}
          - name: {{ .name }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: TLS_SKIP_VERIFY
              value: "{{ .Values.env.tls_skip_verify }}"
            - name: PAIRING_ENDPOINT
              value: "{{ .Values.env.pairing_endpoint }}"
            - name: TOKEN_ENDPOINT
              value: "{{ .Values.env.token_endpoint }}"
            - name: CLUSTER_CREDS_SECRET
              value: "{{ .Values.env.cluster_creds_secret }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}