# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: v1
kind: Service
metadata:
  name: {{ include "cloud-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    release: {{ .Release.Name }}
spec:
  {{- if .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  selector:
    app: {{ include "cloud-operator.name" . }}
    release: {{ .Release.Name }}
  ports:
    - name: http-falco
      protocol: TCP
      port: 5000
      targetPort: 5000
    - name: ipfix-collector
      protocol: UDP
      port: 4789
      targetPort: 4789