# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloud-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cloud-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 65532
      priorityClassName: {{ .Values.priorityClassName }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
          {{- range .Values.imagePullSecrets }}
          - name: {{ .name }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: TLS_SKIP_VERIFY
              value: "{{ .Values.env.tlsSkipVerify }}"
            - name: ONBOARDING_ENDPOINT
              value: "{{ .Values.env.OnboardingEndpoint }}"
            - name: TOKEN_ENDPOINT
              value: "{{ .Values.env.tokenEndpoint }}"
            - name: CLUSTER_CREDS_SECRET
              value: "clustercreds"
            - name: ONBOARDING_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: onboardingcreds
                  key: "client_id"
            - name: ONBOARDING_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: onboardingcreds
                  key: "client_secret"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}