# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloud-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cloud-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      securityContext:
        fsGroup: 65532
      priorityClassName: {{ .Values.priorityClassName }}
      serviceAccountName: {{ .Values.serviceAccount.name }}
      imagePullSecrets:
          {{- range .Values.imagePullSecrets }}
          - name: {{ .name }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 65532
            runAsGroup: 65532
            capabilities:
              drop:
                - ALL
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
            - containerPort: 5000
            - containerPort: 4739
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: CLUSTER_CREDS_SECRET
              value: "clustercreds"
            - name: ONBOARDING_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: onboardingcreds
                  key: "client_id"
            - name: ONBOARDING_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: onboardingcreds
                  key: "client_secret"
            - name: ONBOARDING_ENDPOINT
              value: "{{ .Values.env.onboardingEndpoint }}"
            - name: TOKEN_ENDPOINT
              value: "{{ .Values.env.tokenEndpoint }}"
            - name: TLS_SKIP_VERIFY
              value: "{{ .Values.env.tlsSkipVerify }}"
            - name: STREAM_KEEPALIVE_PERIOD_KUBERNETES_RESOURCES
              value: "{{ .Values.env.streamKeepalivePeriods.kubernetes_resources }}"
            - name: STREAM_KEEPALIVE_PERIOD_KUBERNETES_NETWORK_FLOWS
              value: "{{ .Values.env.streamKeepalivePeriods.kubernetes_network_flows }}"
            - name: STREAM_KEEPALIVE_PERIOD_LOGS
              value: "{{ .Values.env.streamKeepalivePeriods.logs }}"
            - name: STREAM_KEEPALIVE_PERIOD_CONFIGURATION
              value: "{{ .Values.env.streamKeepalivePeriods.configuration }}"
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STREAM_SUCCESS_PERIOD_CONNECT
              value: "{{ .Values.env.streamSuccessPeriods.connect }}"
            - name: STREAM_SUCCESS_PERIOD_AUTH
              value: "{{ .Values.env.streamSuccessPeriods.auth }}"
            - name: HTTPS_PROXY
              value: "{{ .Values.env.httpsProxy | default "" }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: gops-volume
              mountPath: /var/run/gops
            - name: template-volume
              mountPath: /template-storage
      volumes:
        - name: gops-volume
          emptyDir:
            medium: Memory
            sizeLimit: 10Mi
        - name: template-volume
          configMap:
            name: template-set-config
