apiVersion: v1
kind: Secret
metadata:
  name: clustercreds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque