# Copyright 2024 Illumio, Inc. All Rights Reserved.

{{- if and (not .Values.clusterCredsSecret.disableSecretCreation) (or (.Values.clusterCredsSecret.forceSecretCreation) (not (lookup "v1" "Secret" .Release.Namespace "clustercreds"))) -}}
apiVersion: v1
kind: Secret
metadata:
  name: clustercreds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/resource-policy": keep
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
data:
  client_id: "{{ .Values.clusterCredsSecret.clientId | b64enc }}"
  client_secret: "{{ .Values.clusterCredsSecret.clientSecret | b64enc }}"
{{- end -}}
