# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "cloud-operator.fullname" . }}
  labels:
    {{- include "cloud-operator.labels" . | nindent 4 }}rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["get", "list", "watch"]