apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cloud-operator.fullname" . }}
  namespace: {{ .Values.defaultNamespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "cloud-operator.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ include "cloud-operator.name" . }}
        release: {{ .Release.Name }}
    spec:
      imagePullSecrets:
          {{- range .Values.imagePullSecrets }}
          - name: {{ .name }}
          {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            - name: TLS_SKIP_VERIFY
              value: "{{ .Values.env.tls_skip_verify }}"
            - name: PAIRING_ADDRESS
              value: "{{ .Values.env.pairing_address }}"
            - name: TOKEN_ENDPOINT
              value: "{{ .Values.env.token_endpoint }}"
            - name: DEPLOYED_SECRET
              value: "{{ .Values.env.deployed_secret }}"
            - name: OAUTH_SECRET
              value: "{{ .Values.env.oauth_secret }}"
          resources:
            {{- toYaml .Values.resources | nindent 12 }}