apiVersion: v1
kind: ConfigMap
metadata:
  name: falco-rules
  namespace: {{ .Release.Namespace }}
  labels:
    app: falco
data:
  falco_rules.yaml: |
    # Custom Falco Rules

    - rule: Write below etc
      desc: Detect any write below /etc
      condition: evt.type in (open, openat) and evt.dir = < and fd.name startswith /etc
      output: "File below /etc opened for writing (user=%user.name command=%proc.name parent=%proc.pname file=%fd.name)"
      priority: WARNING
      tags: [filesystem, mitre_persistence]

    - rule: Launch Suspicious Shell in Container
      desc: A shell was run inside a container.
      condition: evt.type in (execve) and container.id != host and proc.name in (sh, bash, zsh, csh)
      output: "Suspicious shell activity detected (user=%user.name container=%container.id)"
      priority: NOTICE
      tags: [container, shell, mitre_execution]

    - rule: Create/Modify Binary Directory
      desc: Detect create or modify binary directory
      condition: evt.type in (open, openat) and evt.dir = < and fd.directory in (/bin, /sbin, /usr/bin, /usr/sbin)
      output: "Binary directory modified (user=%user.name command=%proc.name parent=%proc.pname file=%fd.name)"
      priority: WARNING
      tags: [filesystem, mitre_persistence]

    - rule: Unexpected Network Connection
      desc: Detect unexpected network connection
      condition: evt.type in (connect) and fd.sip != 127.0.0.1
      output: "Unexpected network connection detected (command=%proc.name user=%user.name destination=%fd.sip)"
      priority: WARNING
      tags: [network, mitre_command_and_control]