apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: falco-driver-loader
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: falco-driver-loader
  template:
    metadata:
      labels:
        app: falco-driver-loader
    spec:
      containers:
        - name: falco-driver-loader
          image: docker.io/falcosecurity/falco-driver-loader:0.39.1
          imagePullPolicy: IfNotPresent
          args:
            - auto
          securityContext:
            privileged: true
          volumeMounts:
            - mountPath: /root/.falco
              name: root-falco-fs
            - mountPath: /host/proc
              name: proc-fs
              readOnly: true
            - mountPath: /host/boot
              name: boot-fs
              readOnly: true
            - mountPath: /host/lib/modules
              name: lib-modules
            - mountPath: /host/usr
              name: usr-fs
              readOnly: true
            - mountPath: /host/etc
              name: etc-fs
              readOnly: true
            - mountPath: /etc/falco/config.d
              name: specialized-falco-configs

      volumes:
      - name: specialized-falco-configs
        emptyDir: {}
      - name: root-falco-fs
        emptyDir: {}  
      - name: boot-fs
        hostPath:
          path: /boot
      - name: lib-modules
        hostPath:
          path: /lib/modules
      - name: proc-fs
        hostPath:
          path: /proc
      - name: usr-fs
        hostPath:
          path: /usr
      - name: etc-fs
        hostPath:
          path: /etc
      