# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-falco
  namespace: {{ .Values.defaultNamespace }}
spec:
  podSelector: {}  # Apply to all pods in the illumio-cloud namespace
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: In
            values:
              - {{ .Values.falco.namespace }}
  - from:
    - namespaceSelector:
        matchExpressions:
          - key: kubernetes.io/metadata.name
            operator: In
            values:
              - {{ .Values.openshift.ovnk_namespace }}