# Copyright 2025 Illumio, Inc. All Rights Reserved.

apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-network-flow-export
  namespace: {{ .Values.defaultNamespace }}
spec:
  podSelector: {}
  policyTypes:
    - Ingress
  ingress:
    # Allow flow export HTTP requests from Falco.
    - ports:
        - protocol: TCP
          port: 5000
      from:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: {{ .Values.falco.namespace }}
          podSelector: {}
    # Allow IPFIX-over-UDP packets from the ovs-vswitchd daemon
    # that runs on every worker node in OpenShift OVN-k clusters.
    - ports:
        - protocol: UDP
          port: {{ .Values.env.ipfixCollectorPort }}
      {{- if .Values.openshift.workerNodeCidrs }}
      from:
        {{- range .Values.openshift.workerNodeCidrs }}
        - ipBlock:
            cidr: "{{.}}"
        {{- end }}
      {{- end }}
