apiVersion: v1
kind: Secret
metadata:
  name: onboardingcreds
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ include "cloud-operator.name" . }}
    chart: {{ include "cloud-operator.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  client-id: {{ .Values.onboardingClientId | b64enc }}
  secret-id: {{ .Values.onboardingClientSecret | b64enc }}