# Copyright 2024 Illumio, Inc. All Rights Reserved.

apiVersion: v1
kind: Secret
metadata:
  name: onboardingcreds
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "cloud-operator.labels" . | nindent 4 }}
type: Opaque
data:
  client_id: {{ .Values.onboardingSecret.clientId | b64enc }}
  client_secret: {{ .Values.onboardingSecret.clientSecret | b64enc }}
