name: 'Generate Helm Schema'
description: 'Checkout code, set up Helm, generate schema, and check for changes'
outputs:
  changes:
    description: 'Whether there are changes to the schema'
    value: ${{ steps.git-check.outputs.changes }}
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: "v3.16.4"
        
    - name: Generate schema
      uses: losisin/helm-values-schema-json-action@v1
      with:
        path: cloud-operator
        values-file: values.yaml
        schema-file: values.schema.json
        
    - name: Check for changes
      id: git-check
      shell: bash
      run: |
        git diff --exit-code cloud-operator/values.schema.json || echo "changes=true" >> $GITHUB_OUTPUT