name: "Generate Helm Schema"
description: "Set up Helm, generate schema, and check for changes"
outputs:
  changes:
    description: "Whether there are changes to the schema"
    value: ${{ steps.git-check.outputs.changes }}
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: "v3.18.5"

    - name: Generate schema
      uses: losisin/helm-values-schema-json-action@v1
      with:
        working-directory: cloud-operator
        input: values.yaml
        output: values.schema.json

    - name: Check for changes
      id: git-check
      shell: bash
      run: |
        git diff --exit-code cloud-operator/values.schema.json || echo "changes=true" >> $GITHUB_OUTPUT
