name: 'Generate Helm Schema'
description: 'Set up Helm, generate schema, and check for changes'
outputs:
  changes:
    description: 'Whether there are changes to the schema'
    value: ${{ steps.git-check.outputs.changes }}
  diff:
    description: 'The diff between the current and generated schema'
    value: ${{ steps.git-check.outputs.diff }}
runs:
  using: "composite"
  steps:
    - name: Set up Helm
      uses: azure/setup-helm@v4.2.0
      with:
        version: "v3.16.4"

    - name: Generate schema
      uses: losisin/helm-values-schema-json-action@v1
      with:
        path: cloud-operator
        values-file: values.yaml
        schema-file: values.schema.json

    - name: Check for changes
      id: git-check
      shell: bash
      run: |
        # Capture the diff content
        DIFF=$(git diff cloud-operator/values.schema.json)
        # Check if there are changes
        git diff --exit-code cloud-operator/values.schema.json || echo "changes=true" >> $GITHUB_OUTPUT
        # Escape newlines and quotes for GitHub Actions
        DIFF="${DIFF//'%'/'%25'}"
        DIFF="${DIFF//$'\n'/'%0A'}"
        DIFF="${DIFF//$'\r'/'%0D'}"
        # Output the diff
        echo "diff<<EOF" >> $GITHUB_OUTPUT
        echo "$DIFF" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT
