name: Build and Push Docker Image

on:
  push:
    branches:
      - main
    #   - revise-helm-default-values

permissions:
  # Required to generate OIDC tokens for `sigstore/cosign-installer` authentication
  id-token: write

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.6.0

      - name: Check Cosign install
        run: cosign version

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Getting image tag
        id: tag
        run: 
          if [ "${{ github.ref_name }}" == "${{ github.event.repository.default_branch }}" ]; then
              echo tag=latest >> $GITHUB_OUTPUT
          else
              echo tag=${{ github.ref_name }} >> $GITHUB_OUTPUT
          fi

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          build-args: |
            VERSION=${{ steps.tag.outputs.tag }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.VERSION }}
            ghcr.io/${{ github.repository }}:latest
      - name: Sign the images with GitHub OIDC Token
        env:
            DIGEST: ${{ steps.build-and-push.outputs.digest }}
            TAG: ${{ steps.tag.outputs.tag }}
        run: cosign sign --yes ${tag}@${DIGEST}