name: Go

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '^1.24.2'

    - name: Install dependencies
      run: go mod tidy

    - name: Debug Proxy Environment Variables
      run: env | grep -i proxy

    - name: Unset Proxy Variables for Tests
      run: |
        unset HTTPS_PROXY
        unset HTTP_PROXY

    - name: Run tests
      env:
        NO_PROXY: "localhost,127.0.0.1"
      run: go test -v ./internal/controller/...