name: Push Helm Chart

on:
  push:
    tags:
      - "v*"

jobs:
  push-helm-chart:
    runs-on: ubuntu-latest

    steps:

        - name: Checkout code
          uses: actions/checkout@v4
        
        - name: Set up Helm
          uses: azure/setup-helm@v1
          with:
            version: v3.8.0

        - name: Log in to GitHub Container Registry for Helm
          run: echo ${{ secrets.GITHUB_TOKEN }} | helm registry login ghcr.io --username ${{ github.actor }} --password-stdin
        - name: Determine version from Git
          id: determine_version
          run: |
            # Get the latest tag reachable from the current commit
            VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
            if [ -z "$VERSION" ]; then
            # If no tag is found, use the commit SHA
            VERSION=${GITHUB_SHA}
            fi
            echo "VERSION=$VERSION" >> $GITHUB_ENV

        - name: Update Helm chart version
          run: |
            # Update the version in Chart.yaml
            sed -i "s/^version:.*/version: ${VERSION}/" cloud-operator/Chart.yaml
            # Update the tag in values.yaml
            sed -i "s/^  tag:.*/  tag: ${VERSION}/" cloud-operator/values.yaml

        - name: Package Helm chart
          run: helm package cloud-operator/ --version ${{ env.VERSION }}
        
        - name: Push Helm chart to GHCR
          run: |
            CHART_NAME=$(basename cloud-operator)
            helm push ${CHART_NAME}-$${{ env.VERSION }}.tgz oci://ghcr.io/${{ github.repository_owner }}/charts
