name: Scan Docker Image with Grype

on:
  push:
    branches:
      - main

jobs:
  scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Red Hat Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      # Not sure if I need to pull from Quay here since Grpye should be able to grab image to scan since ill have logged in.
      - name: Pull Docker image from Quay
        run: docker pull quay.io/${{ secrets.QUAY_USERNAME }}/cloud-operator:latest

      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin

      - name: Scan Docker image with Grype
        run: grype quay.io/${{ secrets.QUAY_USERNAME }}/cloud-operator:latest --fail-on low