name: Setup for Integration Tests with Fakeserver

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test-deploy-onboard-fakeserver:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64
          build-args: |
            VERSION=${{ steps.meta.outputs.tags }}
          tags: |
            ghcr.io/${{ github.repository }}:${{ steps.meta.outputs.tags }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: "v1.24.0"

      - name: Install Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube

      - name: Start Minikube
        run: |
          minikube start --driver=docker

      - name: Wait for Minikube to be ready
        run: |
          minikube kubectl -- get nodes

      - name: Set up Helm
        uses: azure/setup-helm@v4.2.0
        with:
            version: "v3.16.4"

      - name: Package Helm chart
        run: |
            helm package cloud-operator && kubectl create ns illumio-cloud

      - name: Install Integration Test Dependencies
        run: |
            cd ./fakeserver && go mod tidy && go mod download
